trustification/exhort-java-api

- .github/auto-me-bot.yml
- .github/workflows/pr.yml
- .github/workflows/stage.yml
> ci: added ci workflows for pr and stage

- .github/workflows/release.yml
Trigger the release process only on branches that their name starts with "release/"
> ci: only create release if the merged branch is prefixed with 'release/'

- src/it/simple-modular/src/test/java/simple/modular/Simple_Integration_Test.java
- src/main/java/com/redhat/exhort/Api.java
- src/main/java/com/redhat/exhort/Provider.java
- src/main/java/com/redhat/exhort/impl/ExhortApi.java
- src/main/java/com/redhat/exhort/providers/GoModulesProvider.java
- src/main/java/com/redhat/exhort/providers/JavaMavenProvider.java
- src/main/java/com/redhat/exhort/providers/JavaScriptNpmProvider.java
- src/test/java/com/redhat/exhort/impl/Exhort_Api_Test.java
- src/test/java/com/redhat/exhort/providers/Golang_Modules_Provider_Test.java
- src/test/java/com/redhat/exhort/providers/Java_Maven_Provider_Test.java
- src/test/java/com/redhat/exhort/providers/Javascript_Npm_Provider_Test.java
fix: component analysis sometimes fails to invoke npm ls because of improper location of temp file creation 
test: modify UT and IT tests to take into account failures also, by mocking the http status code to 200
feature: add new component analysis method to enable passing existing manifests from existing directories
test: add tests for new component analysis method with string path argument
fix: add correct error handling for cases in which exhort backend returns errors
> fix: several bug fixes and improvements

- src/main/java/com/redhat/exhort/providers/JavaMavenProvider.java
- src/main/java/com/redhat/exhort/tools/Operations.java
When `mvn` command execution fails, add the output to the exception message. 
So that, the command execution failure details can be found in the IDE (e.g. IntelliJ IDEA) logs, which helps users to troubleshoot the issues.
> fix: log the detailed error message for mvn execution failures

- src/main/java/com/redhat/exhort/providers/GoModulesProvider.java
- src/test/java/com/redhat/exhort/providers/Golang_Modules_Provider_Test.java
- src/test/resources/tst_manifests/golang/go_mod_no_path/expected_sbom_component_analysis.json
- src/test/resources/tst_manifests/golang/go_mod_no_path/expected_sbom_stack_analysis.json
- src/test/resources/tst_manifests/golang/go_mod_no_path/go.mod
Fix a scenario of parsing module name in go.mod, for example: https://github.com/pstember/go-goof/blob/73c2655d0f64cbd4ce8793d9819215ea337b8156/go.mod#L1
> fix: parsing go module name

- src/main/java/com/redhat/exhort/impl/ExhortApi.java
- src/main/java/com/redhat/exhort/providers/PythonPipProvider.java
- src/main/java/com/redhat/exhort/sbom/CycloneDXSbom.java
- src/main/java/com/redhat/exhort/sbom/Sbom.java
- src/test/java/com/redhat/exhort/providers/Python_Provider_Test.java
- src/test/resources/tst_manifests/pip/pip_requirements_txt_ignore/expected_component_sbom.json
- src/test/resources/tst_manifests/pip/pip_requirements_txt_ignore/expected_stack_sbom.json
- src/test/resources/tst_manifests/pip/pip_requirements_txt_no_ignore/expected_component_sbom.json
- src/test/resources/tst_manifests/pip/pip_requirements_txt_no_ignore/expected_stack_sbom.json
Remove dummy root component from sbom for python/pip, as in python you don't have a root component, just a list of required packages/modules in requirements.txt
For the purpose, Added new sbom generic feature, to remove from sbom the root component :
from components list.
from dependencies list.
and from metadata
currently it will be used only by Python/pip.
related to: https://github.com/RHEcosystemAppEng/exhort-javascript-api/pull/58
> fix: remove dummy root component from sbom for python/pip

- src/main/java/com/redhat/exhort/providers/JavaMavenProvider.java
- src/test/resources/tst_manifests/maven/deps_no_trivial_with_ignore/expected_stack_sbom.json
Change the logic of exhortignore feature in sbom creation for maven package manager to be sensitive ( was insensitive), that is , only delete exhortignored artifacts from sbom' components and dependencies lists,  but not their transitive ( their transitive will remain as components, whether they're transitive of other non exhortignored direct artifacts or not (as orphaned components)).
> fix:  turn exhortignore strategy into sensitive

- .github/workflows/release.yml
- README.md
chore: prepare 0.0.2 release
ci: add python support for release workflow
docs: fix typo in documentation
> chore: prepare 0.0.2 release

- .github/workflows/release.yml
- README.md
- src/main/java/com/redhat/exhort/providers/JavaMavenProvider.java
- src/test/resources/tst_manifests/maven/deps_no_trivial_with_ignore/expected_stack_sbom.json
fix: turn exhortignore strategy into sensitive
docs: fix typo in documentation
ci: fix changelog of release and README.md update
> chore: prepare release 0.0.2 + CI fixes.

- src/main/java/com/redhat/exhort/providers/PythonPipProvider.java
In addition to reading environment variable `EXHORT_PYTHON_VIRTUAL_ENV` to determining if using python virtual environment, also ready system property.
> fix: read property to determine if using python virtual env

- src/main/java/com/redhat/exhort/utils/PythonControllerBase.java
- src/test/java/com/redhat/exhort/utils/PythonControllerBaseTest.java
Splitting `pip show` results with `---` could generate incorrect results when a package contains license information.
An example of such package can be generated by executing `pip3 show scipy`.
Code in this PR reads the results of `pip show` line by line, and groups information by packages.
Jira: https://issues.redhat.com/browse/TC-644
> fix: results of pip show are not properly parsed

- src/test/resources/tst_manifests/npm/deps_with_ignore/expected_component_sbom.json
- src/test/resources/tst_manifests/npm/deps_with_no_ignore/expected_component_sbom.json
> fix: ci tests failure

- src/test/java/com/redhat/exhort/providers/Javascript_Npm_Provider_Test.java
- src/test/resources/tst_manifests/npm/deps_with_ignore/expected_component_sbom.json
- src/test/resources/tst_manifests/npm/deps_with_ignore/npm-ls-component.json
- src/test/resources/tst_manifests/npm/deps_with_ignore/npm-ls-stack.json
- src/test/resources/tst_manifests/npm/deps_with_no_ignore/expected_component_sbom.json
- src/test/resources/tst_manifests/npm/deps_with_no_ignore/npm-ls-component.json
- src/test/resources/tst_manifests/npm/deps_with_no_ignore/npm-ls-stack.json
Need to mock interactions with npm package manager in order to achieve the following benefits:
- in order to eliminate the need to change expected sbom files (due to versions bump)
- in order to focus merely on API logic and not on integrations of API with npm package manager
- in order to reduce tests times
> test: mock npm data provider

- src/main/java/com/redhat/exhort/impl/ExhortApi.java
- src/main/resources/exhort/openapi.yaml
Integrate multi-source v4 endpoint of exhort backend with Java API
> feat: integrate multi-source v4 endpoint

- src/main/java/com/redhat/exhort/impl/ExhortApi.java
feat: map providers' user setting to request header for authentication, in case the provider requires basic authentication ( user + token)
> feat: map providers' user setting to request header for authentication 

- pom.xml
- src/main/java/com/redhat/exhort/providers/JavaMavenProvider.java
When there is in dependency tree an artifact with classifier, the components are in different positions( the version) in the string, and there are 6 parts instead of 5 parts, so need to identify it , and parse it correctly.
For example:
5 parts ( no classifier):
com.google.guava:guava:jar:10.0.1:compile
6 parts ( with classifier):
org.sonatype.sisu:sisu-guice:jar:no_aop:3.1.0:compile
Fixes: https://issues.redhat.com/browse/TC-766
> fix: maven - error parsing artifact with classifier

- src/main/java/com/redhat/exhort/providers/JavaMavenProvider.java
Before being excluded from sbom creation, test scoped artifacts are parsed wrongly, hence causing an exception
> fix: regressive issue with test artifacts

- src/main/java/com/redhat/exhort/providers/PythonPipProvider.java
- src/main/java/com/redhat/exhort/utils/PythonControllerBase.java
Implement [PR #92](https://github.com/RHEcosystemAppEng/exhort-javascript-api/pull/92/) for Java-API 
Developed to ease and make life easier for running rhda analysis for python pip requirements.txt manifest, as every requirements.txt with certain versions for its package is tailored for a certain python version. 
This enables  separating the installation of the requirements.txt from the machine that runs the RHDA analysis ( will be used mainly from jenkins pipelines together with RHDA Jenkins pipeline).
> feat: get output of pip commands from env variables

- src/main/java/com/redhat/exhort/providers/GoModulesProvider.java
- src/main/java/com/redhat/exhort/utils/PythonControllerBase.java
- src/test/java/com/redhat/exhort/providers/Golang_Modules_Provider_Test.java
- src/test/resources/msc/golang/mvs_logic/expected_sbom_stack_analysis.json
- src/test/resources/msc/golang/mvs_logic/go.mod
Add functionallity of EXHORT_GO_MVS_LOGIC_ENABLED setting
Summary:
In case go  modules stack analysis , it happens occasionally that the different transitive packages uses the same module( same major version) but each one, with different minor version ( packages with same namespace and name that contain different major versions are different packages, for example gopkg.in/yaml.v2 and /gopkg.in/yaml.v3 are two different packages/ modules).
In such case, the analysis showing for each package , all its transitive according to the go module tree graph, with the original version defined in the transitive module' go.mod file, and not the version picked for building the final executable binary ( using go build or go install commands)
for example, if application `c` has 2 modules/packages - `a` …
> feat: add functionallity of EXHORT_GO_MVS_LOGIC_ENABLED setting

- pom.xml
- src/main/java/com/redhat/exhort/impl/ClientTraceIdSimpleFormatter.java
- src/main/java/com/redhat/exhort/impl/ExhortApi.java
- src/main/java/com/redhat/exhort/impl/RequestManager.java
- src/main/java/com/redhat/exhort/logging/LoggersFactory.java
- src/main/java/com/redhat/exhort/providers/GoModulesProvider.java
- src/main/java/com/redhat/exhort/providers/JavaMavenProvider.java
- src/main/java/com/redhat/exhort/providers/PythonPipProvider.java
- src/main/java/com/redhat/exhort/sbom/CycloneDXSbom.java
- src/main/java/com/redhat/exhort/utils/PythonControllerBase.java
When EXHORT_DEBUG=true , and you are using a plugin that uses this library ( for example Intelli-J RHDA Plugin), then when you opening several supported manifest files concurrently, and exit and re-enter them to check something, you can easily lose yourself among the huge dumps of generated logs from the library, hence we need to associate each request (logs)  invoked by a thread by a unique identifier ( UUID will be enough for this purpose), so it will be attached to every log message.
As a Consequence and because it was needed, i developed also a very simple "Logging Framework" That tailored to the Specific needs of the API, so the process it as follows:
1.For each request, generate an  exhort-client-trace-id UUID value.
2. Transplant the generated exhort-client-trace-id into all log …
> feat: add exhort client trace id to API library

- src/main/java/com/redhat/exhort/impl/ExhortApi.java
- src/main/java/com/redhat/exhort/providers/JavaScriptNpmProvider.java
in case directory has spaces, need to invoke npm ls command from that directory , without prefix flag, this change fixes an error of not finding the package-lock.json in a directory that contains spaces
> fix: npm - cannot find the generated package-lock.json

- src/main/java/com/redhat/exhort/providers/PythonPipProvider.java
- src/test/resources/tst_manifests/pip/pip_requirements_txt_ignore/expected_component_sbom.json
- src/test/resources/tst_manifests/pip/pip_requirements_txt_ignore/expected_stack_sbom.json
- src/test/resources/tst_manifests/pip/pip_requirements_txt_no_ignore/expected_component_sbom.json
- src/test/resources/tst_manifests/pip/pip_requirements_txt_no_ignore/expected_stack_sbom.json
> fix: revive root component in generated sbom for python pip

- README.md
- src/main/java/com/redhat/exhort/providers/PythonPipProvider.java
- src/main/java/com/redhat/exhort/utils/PythonControllerBase.java
- src/main/java/com/redhat/exhort/utils/PythonDependency.java
- src/main/java/module-info.java
- src/test/java/com/redhat/exhort/providers/Python_Provider_Test.java
- src/test/resources/tst_manifests/pip/pipdeptree.json
Improve Python build tree Performance in EXHORT-JAVA-API
JIRA: https://issues.redhat.com/browse/APPENG-2154
same fix has been done in exhort-javascript-api -> https://github.com/RHEcosystemAppEng/exhort-javascript-api/pull/121
> feat: introduce new flag to avoid using pip freeze and pip show

- src/main/java/com/redhat/exhort/impl/ExhortApi.java
- src/main/java/com/redhat/exhort/impl/RequestManager.java
> fix: bug of ex-client-trace-id not cleared in the end

- src/main/java/com/redhat/exhort/Provider.java
- src/main/java/com/redhat/exhort/providers/JavaScriptNpmProvider.java
- src/main/java/com/redhat/exhort/tools/Ecosystem.java
- src/test/java/com/redhat/exhort/providers/Golang_Modules_Provider_Test.java
- src/test/java/com/redhat/exhort/tools/Ecosystem_Test.java
Follow up PR to validate lock files exist when returning the Provider.
**Related issue (if any):** fixes #113 
> fix: validate if npm has lock file

- src/main/java/com/redhat/exhort/providers/JavaScriptNpmProvider.java
- src/main/java/com/redhat/exhort/providers/JavaScriptPnpmProvider.java
- src/main/java/com/redhat/exhort/providers/JavaScriptProvider.java
- src/main/java/com/redhat/exhort/providers/JavaScriptYarnProvider.java
fix: fix incorrect pathEnv() implementation in JavaScriptProvider subclass
see more info in the bug report https://github.com/trustification/exhort-java-api/issues/132
**Related issue (if any):** fixes https://github.com/trustification/exhort-java-api/issues/132
> fix: fix incorrect pathEnv() implementation in JavaScriptProvider subclass

- src/main/java/com/redhat/exhort/image/ImageUtils.java
- src/main/java/com/redhat/exhort/providers/GoModulesProvider.java
- src/main/java/com/redhat/exhort/providers/GradleProvider.java
- src/main/java/com/redhat/exhort/providers/JavaMavenProvider.java
- src/main/java/com/redhat/exhort/providers/JavaScriptProvider.java
- src/main/java/com/redhat/exhort/providers/PythonPipProvider.java
- src/main/java/com/redhat/exhort/tools/Ecosystem.java
- src/main/java/com/redhat/exhort/tools/Operations.java
- src/test/java/com/redhat/exhort/image/ImageRefTest.java
- src/test/java/com/redhat/exhort/image/ImageUtilsTest.java
- src/test/java/com/redhat/exhort/impl/ExhortApiIT.java
- src/test/java/com/redhat/exhort/impl/Exhort_Api_Test.java
- src/test/java/com/redhat/exhort/providers/Gradle_Provider_Test.java
- src/test/java/com/redhat/exhort/providers/Java_Maven_Provider_Test.java
- src/test/java/com/redhat/exhort/providers/Javascript_Provider_Test.java
fix: validate executable binary in the path before running the analysis.
**Related issue (if any):** https://github.com/redhat-developer/intellij-dependency-analytics/issues/182
> fix: validate executable binary in the path before running the analysis.

- src/main/java/com/redhat/exhort/providers/JavaScriptProvider.java
- src/main/java/com/redhat/exhort/tools/Operations.java
- src/test/java/com/redhat/exhort/providers/Javascript_Envs_Test.java
fix: add necessary envs (if has) to validate executable binary in the PATH
**Related issue (if any):** amend the fix made in https://github.com/trustification/exhort-java-api/pull/134
> fix: add necessary envs (if has) to validate executable binary in the PATH

- src/test/resources/tst_manifests/pip/pip-freeze-all.txt
- src/test/resources/tst_manifests/pip/pip-show.txt
- src/test/resources/tst_manifests/pip/pip_requirements_txt_ignore/expected_component_sbom.json
- src/test/resources/tst_manifests/pip/pip_requirements_txt_ignore/expected_stack_sbom.json
- src/test/resources/tst_manifests/pip/pip_requirements_txt_ignore/requirements.txt
- src/test/resources/tst_manifests/pip/pip_requirements_txt_no_ignore/expected_component_sbom.json
- src/test/resources/tst_manifests/pip/pip_requirements_txt_no_ignore/expected_stack_sbom.json
- src/test/resources/tst_manifests/pip/pip_requirements_txt_no_ignore/requirements.txt
- src/test/resources/tst_manifests/pip/pipdeptree.json
chore: update python test dependency immutables to be compatible with higher version python
`Python_Provider_Test` fails with a higher Python version (3.13) in local.
immutables 0.19 is not compatible with python version. E.g. 3.13. It's only compatible with Python versions until 3.11.
> chore: update python test dependency immutables to be compitable with higher version python

- src/main/java/com/redhat/exhort/providers/YarnBerryProcessor.java
- src/main/java/com/redhat/exhort/tools/Operations.java
Prefer stdout over stderr to cover cases when there are only warnings. If only error is present and no stdout is returned then the error will be returned instead.
**Related issue (if any):** fixes #154
> fix: prefer stdout
