.github/workflows/pr.yml
=> ci: fixed pr workflow identation error

.github/workflows/stage.yml
=> ci: staging workflow now create github releases

src/it/simple-modular/pom.xml
=> fix: integration test core module unpninned

src/test/java/com/redhat/crda/impl/Crda_Api_Test.java, src/test/java/module-info.test
=> test: fixed test class package name

.github/CODE_OF_CONDUCT.md, .github/ISSUE_TEMPLATE/bug_report.yml, .github/ISSUE_TEMPLATE/config.yml, .github/ISSUE_TEMPLATE/feature_request.yml, .github/PULL_REQUEST_TEMPLATE.md, CONTRIBUTING.md, DCO, README.md, pom.xml, src/main/java/com/redhat/crda/Api.java, src/main/java/com/redhat/crda/Provider.java, src/main/java/com/redhat/crda/impl/CrdaApi.java, src/main/java/com/redhat/crda/impl/package-info.java, src/main/java/com/redhat/crda/package-info.java, src/main/java/com/redhat/crda/providers/JavaMavenProvider.java, src/main/java/com/redhat/crda/providers/package-info.java, src/main/java/com/redhat/crda/tools/Ecosystem.java, src/main/java/com/redhat/crda/tools/Operations.java, src/main/java/com/redhat/crda/tools/package-info.java
- docs: update pom comments
- docs: update README
- docs: added DCO doc
- docs: updated CONTRIBUTING doc
- docs: added code of conduct doc
- docs: added community docs
- docs: added code walkthrough to CONTRIBUTING.md
- docs: updated javadoc comments
=> docs: update repository docs and javadoc comments

README.md, src/it/simple-modular/src/main/java/simple/modular/ApiWrapper.java, src/it/simple-modular/src/test/java/simple/modular/Simple_Integration_Test.java, src/main/java/com/redhat/crda/Api.java, src/main/java/com/redhat/crda/impl/CrdaApi.java, src/test/java/com/redhat/crda/impl/Crda_Api_Test.java
=> refactor: small refactoring, mostly of names

src/it/simple-modular/pom.xml, src/it/simple-modular/src/test/java/module-info.test, src/it/simple-modular/src/test/java/simple/modular/Simple_Integration_Test.java, src/main/java/com/redhat/crda/impl/CrdaApi.java, src/main/resources/crda_backend/openapi.yaml
=> chore: update openapi spec and integration tests

README.md
=> docs: added gradle usage example in README

.github/workflows/pr.yml, .github/workflows/stage.yml, CONTRIBUTING.md, pom.xml, src/it/simple-modular/pom.xml, src/main/java/com/redhat/crda/Provider.java, src/main/java/com/redhat/crda/impl/CrdaApi.java, src/main/java/com/redhat/crda/providers/JavaMavenProvider.java, src/main/java/com/redhat/crda/tools/Ecosystem.java, src/test/java/com/redhat/crda/providers/Java_Maven_Provider_Test.java, src/test/java/com/redhat/crda/tools/Ecosystem_Test.java
This project's main client [intellij-dependency-analytics](https://github.com/redhat-developer/intellij-dependency-analytics) requires Java 11.
I'm sad. I want records!
=> chore: downgrade project java version from 17 to 11

CONTRIBUTING.md, README.md, src/main/java/com/redhat/crda/impl/CrdaApi.java
=> chore: added env variable for the vendor tokens and backend url

src/main/resources/crda_backend/openapi.yaml
See https://github.com/RHEcosystemAppEng/crda-backend/pull/50
=> chore: update api spec for adding sbom to the stack analytics endpoint

README.md, pom.xml, src/main/java/com/redhat/crda/Provider.java, src/main/java/com/redhat/crda/providers/JavaMavenProvider.java, src/main/java/com/redhat/crda/tools/Operations.java, src/test/java/com/redhat/crda/tools/Operations_Test.java, src/test/java/module-info.test
=> chore: added mechanism for custom executable paths

README.md
=> docs: readme typos

src/main/java/com/redhat/crda/impl/CrdaApi.java, src/main/java/com/redhat/crda/tools/Operations.java
=> chore: fixed typos in code

.github/workflows/stage.yml
=> ci: prevent staging workflow from running on forks

README.md, src/main/java/com/redhat/crda/impl/CrdaApi.java, src/main/java/com/redhat/crda/tools/Operations.java, src/test/java/com/redhat/crda/impl/Crda_Api_Test.java, src/test/java/com/redhat/crda/tools/Operations_Test.java
- chore: look for customizebles in java properties as well as environment variables
- docs: update doca for customizing via properties
=> feat: allow customizing via java properties

README.md
=> docs: added supported list to readme

README.md
=> docs: fixed readme typos

.github/workflows/oapi_spec.yml
=> ci: added workflow verifying openapi spec generation

CONTRIBUTING.md, pom.xml, src/main/java/com/redhat/crda/providers/JavaMavenProvider.java, src/test/resources/tst_manifests/pom_deps_with_ignore_on_artifact/component_expected_json, src/test/resources/tst_manifests/pom_deps_with_ignore_on_dependency/component_expected_json, src/test/resources/tst_manifests/pom_deps_with_ignore_on_group/component_expected_json, src/test/resources/tst_manifests/pom_deps_with_ignore_on_version/component_expected_json
- docs: small fix
- fix: component analysis fails to ignore dependencies
=> fix: component analysis fails to ignore dependencies

src/main/java/com/redhat/exhort/impl/ExhortApi.java
- refactor: change backend default route  to single source (single vendor)  version
=> refactor: change backend default route 

.github/workflows/release.yml
=> chore: change typo of main branch name

.github/workflows/release.yml
=> chore: trigger workflow also by changing the workflow file

.github/workflows/release.yml, README.md, pom.xml, src/test/java/com/redhat/exhort/providers/GoModulesMainModuleVersionTest.java
Create a maven Release Workflow
=> ci: build release workflow for maven

.github/workflows/release.yml
=> chore: need to checkout github.head_ref

.github/workflows/release.yml
=> chore: need to trigger workflow only when PR is closed

.github/workflows/release.yml, README.md, pom.xml, src/test/java/com/redhat/exhort/providers/GoModulesMainModuleVersionTest.java
ci: Create maven release workflow
=> ci: Create maven release workflow

src/test/java/com/redhat/exhort/providers/Javascript_Npm_Provider_Test.java, src/test/resources/tst_manifests/npm/deps_with_ignore/expected_stack_sbom.json, src/test/resources/tst_manifests/npm/deps_with_ignore/package-lock.json, src/test/resources/tst_manifests/npm/deps_with_no_ignore/expected_stack_sbom.json, src/test/resources/tst_manifests/npm/deps_with_no_ignore/package-lock.json
npm tests are failing because dynamically created package-lock.json changed every couple of days 
Need to propagate hardcoded package-lock.json from test directory to temp directory ( where package.json is executed from).
=> test: npm tests are failing because dynamically created package-lock

src/main/java/com/redhat/exhort/impl/ExhortApi.java, src/test/java/com/redhat/exhort/impl/Exhort_Api_Test.java
https://issues.redhat.com/browse/APPENG-1997
Enable  attaching `rhda-token` header to request sent to exhort backend, if exists as environment variable / (key,value) in java properties.
=> feat: attach to request rhda-token if exists in env/property

.github/workflows/release.yml, README.md, src/main/java/com/redhat/exhort/providers/JavaMavenProvider.java, src/test/resources/tst_manifests/maven/deps_no_trivial_with_ignore/expected_stack_sbom.json
fix: turn exhortignore strategy into sensitive
docs: fix typo in documentation
ci: fix changelog of release and README.md update
=> chore: prepare 0.0.2 release

catalog-info.yaml
Adding Backstage configurations catalog-info.yaml
=> chore: add backstage configurations catalog-info.yaml

pom.xml
chore: prepare release 0.0.3
test: increase lines code coverage percent
=> chore: prepare release 0.0.3

src/main/java/com/redhat/exhort/impl/ExhortApi.java, src/main/resources/exhort/openapi.yaml
instead of openapi-generator , deprecate openapi-generator from lifecycle build
introduce exhort-api-spec artifact instead of openapi-generator , deprecate openapi-generator from lifecycle build
=> feat: introduce exhort-api-spec artifact 

src/main/java/com/redhat/exhort/api/PackageRef.java, src/main/java/com/redhat/exhort/api/serialization/PackageURLSerializer.java
=> fix: deserialize purls with qualifiers

pom.xml, src/main/java/com/redhat/exhort/impl/ExhortApi.java, src/main/java/com/redhat/exhort/providers/GoModulesProvider.java, src/main/java/com/redhat/exhort/providers/JavaMavenProvider.java, src/main/java/com/redhat/exhort/providers/JavaScriptNpmProvider.java, src/main/java/com/redhat/exhort/providers/PythonPipProvider.java, src/main/java/com/redhat/exhort/sbom/CycloneDXSbom.java, src/main/java/com/redhat/exhort/utils/PythonControllerBase.java
=> feat: improve logging significantly

src/main/java/com/redhat/exhort/impl/ExhortApi.java
=> chore: fix startingtime timestamp of analysis for logs

src/main/java/com/redhat/exhort/providers/JavaScriptNpmProvider.java
1. npm - need to create/refresh package-lock.json anyway
2. npm - in the end of analysis, only delete package-lock.json of component analysis that manifest is passed as content .
=> fix: npm - need to create/refresh package-lock.json anyway

src/main/java/com/redhat/exhort/impl/ExhortApi.java
=> fix: enable EXHORT_DEBUG also from system property

.github/workflows/pr.yml, .github/workflows/release.yml, .github/workflows/stage.yml, pom.xml, src/main/java/com/redhat/exhort/logging/ClientTraceIdSimpleFormatter.java, src/main/java/com/redhat/exhort/logging/LoggersFactory.java, src/main/java/module-info.java
=> ci: add RUN_PYTHON_BIN env var to PR Pipeline

.github/workflows/pr.yml, .github/workflows/release.yml, .github/workflows/stage.yml, src/main/java/com/redhat/exhort/impl/ExhortApi.java, src/main/java/com/redhat/exhort/impl/RequestManager.java, src/main/java/com/redhat/exhort/logging/ClientTraceIdSimpleFormatter.java, src/main/java/com/redhat/exhort/logging/LoggersFactory.java
In case of EXHORT_DEBUG=true, Some log message printed multiple times.
=> fix: some log messages printed multiple times

.github/workflows/release.yml, .github/workflows/stage.yml
=> ci: enable releasing from forks repositories

README.md, pom.xml, src/main/java/com/redhat/exhort/Api.java, src/main/java/com/redhat/exhort/image/Image.java, src/main/java/com/redhat/exhort/image/ImageRef.java, src/main/java/com/redhat/exhort/image/ImageUtils.java, src/main/java/com/redhat/exhort/image/Platform.java, src/main/java/com/redhat/exhort/impl/ExhortApi.java, src/main/java/com/redhat/exhort/providers/JavaMavenProvider.java, src/main/java/com/redhat/exhort/providers/JavaScriptNpmProvider.java, src/main/java/com/redhat/exhort/tools/Operations.java, src/main/java/module-info.java, src/main/resources/exhort/openapi.yaml, src/test/java/com/redhat/exhort/image/ImageRefTest.java, src/test/java/com/redhat/exhort/image/ImageTest.java, src/test/java/com/redhat/exhort/image/ImageUtilsTest.java, src/test/java/com/redhat/exhort/image/PlatformTest.java, src/test/java/com/redhat/exhort/impl/ExhortApiIT.java, src/test/java/com/redhat/exhort/impl/Exhort_Api_Test.java, src/test/java/com/redhat/exhort/providers/Java_Envs_Test.java, src/test/java/com/redhat/exhort/providers/Javascript_Envs_Test.java, src/test/java/com/redhat/exhort/tools/OperationsTest.java, src/test/java/module-info.test, src/test/resources/msc/image/image_reports.json, src/test/resources/msc/image/image_sbom.json, src/test/resources/msc/image/skopeo_inspect_multi_raw.json, src/test/resources/msc/image/skopeo_inspect_single.json, src/test/resources/msc/image/skopeo_inspect_single_raw.json
=> feat: support analyzing images

src/main/java/com/redhat/exhort/impl/ExhortApi.java
=> fix: logs should only printed in EXHORT_DEBUG=true

src/main/java/com/redhat/exhort/providers/GradleProvider.java, src/test/resources/tst_manifests/gradle/deps_with_ignore_full_specification/expected_stack_sbom.json, src/test/resources/tst_manifests/gradle/deps_with_ignore_named_params/expected_stack_sbom.json, src/test/resources/tst_manifests/gradle/deps_with_ignore_notations/expected_stack_sbom.json, src/test/resources/tst_manifests/gradle/deps_with_no_ignore_common_paths/expected_stack_sbom.json
Fixed the duplicates  in gradle stack analysis.
https://issues.redhat.com/browse/APPENG-2425
=> fix: fixed the duplicates  in gradle stack analysis

src/main/java/com/redhat/exhort/providers/GradleProvider.java, src/test/resources/tst_manifests/gradle/deps_with_ignore_notations/expected_component_sbom.json, src/test/resources/tst_manifests/gradle/deps_with_no_ignore_common_paths/expected_component_sbom.json
Retrofits https://github.com/RHEcosystemAppEng/exhort-javascript-api/pull/144 to exhort-java-api 
Fixes: https://issues.redhat.com/browse/TC-1557
=> fix: add and fix missing configurations for gradle ca

.github/auto-me-bot.yml
=> build: remove autome bot

.github/workflows/pr.yml
* Test LTS java versions in CI builds.
* update deprecated gradle task
**Related issue (if any):** fixes #116
=> chore: test LTS Java versions

src/main/java/com/redhat/exhort/Api.java, src/main/java/com/redhat/exhort/sbom/CycloneDXSbom.java, src/main/java/module-info.java, src/test/java/com/redhat/exhort/impl/ExhortApiIT.java, src/test/java/com/redhat/exhort/providers/GoModulesMainModuleVersionTest.java, src/test/java/com/redhat/exhort/providers/PythonEnvironmentExtension.java, src/test/java/com/redhat/exhort/utils/PythonControllerBaseTest.java
There was a typo in the method signature
=> fix: typo in method signature

.github/workflows/release.yml, .github/workflows/stage.yml
The stage workflow is failing due to the make_latest value expecting a string 'false'
**Related issue (if any):**
=> fix: make_latest must be a string

src/main/java/com/redhat/exhort/providers/YarnBerryProcessor.java, src/main/java/com/redhat/exhort/providers/YarnClassicProcessor.java
There was an invalid character in the YarnProcessors Javadoc comments.
Related to #127
=> doc: amend yarn processor comments

README.md, src/main/java/com/redhat/exhort/impl/ExhortApi.java, src/test/java/com/redhat/exhort/impl/Exhort_Api_Test.java
feat: support configure a proxy url for external requests
**Related issue (if any):** fixes #130 
=> feat: support configure a proxy url for external requests

src/main/java/com/redhat/exhort/providers/JavaMavenProvider.java, src/main/java/com/redhat/exhort/tools/Operations.java, src/test/java/com/redhat/exhort/impl/ExhortApiIT.java, src/test/java/com/redhat/exhort/providers/Java_Maven_Provider_Test.java
feat: support configuring maven wrapper
This is the java api part for https://github.com/redhat-developer/intellij-dependency-analytics/issues/171
=> feat: support configuring maven wrapper

src/main/java/com/redhat/exhort/providers/JavaScriptNpmProvider.java, src/main/java/com/redhat/exhort/providers/JavaScriptProvider.java
Use the working dir in the `runProcess` command instead of using `--prefix`
**Related issue (if any):** fixes #164
=> fix: manifest dir as working directory

src/main/java/com/redhat/exhort/providers/GoModulesProvider.java
Use the `json` format for the `go env` command to make it OS agnostic
**Related issue (if any):** fixes #166
=> fix: parse go env in json format

.github/workflows/integration.yml, .github/workflows/pr.yml, .github/workflows/release.yml, .github/workflows/stage.yml, .gitignore, pom.xml
Add integration tests workflow
**Related issue (if any):** 
fixes #150
=> Add integration tests workflow

src/main/java/com/redhat/exhort/providers/JavaMavenProvider.java
Minor update in logging condition to help verify if `mvn` or `mvnw` is used.
=> fix: update for logging
